-- AlterTable
ALTER TABLE `booking` MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'PROCESS') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `riwayat` ADD COLUMN `status` ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'PROCESS') NOT NULL DEFAULT 'PENDING';
